name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  ping_url:
    runs-on: ubuntu-latest
    name: Ping URL
    steps:
      - name: Ping the URL
        uses: soul-wish/ping-url-javascript-action@v1.5
        with:
          url: "https://radio-infu.onrender.com"
